name: DAST Scan with ZAP and Nuclei

on:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write

jobs:
  dast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Start Mutillidae Container
        run: |
          docker run -d -p 8080:80 --name mutillidae citizenstig/dvwa
          sleep 20

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:8080'
          fail_action: false


      - name: Install and Run Nuclei
        run: |
          wget https://github.com/projectdiscovery/nuclei/releases/download/v3.4.5/nuclei_3.4.5_linux_amd64.zip
          unzip -o -qq nuclei_3.4.5_linux_amd64.zip
          chmod +x nuclei
          ./nuclei -version
          ./nuclei -u http://localhost:8080 -json -o nuclei.json


      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: dast-reports
          path: |
            zap_report.html
            zap_report.json
            nuclei.json
