name: DAST Scan with ZAP and Nuclei

on:
push:
branches: [main]

permissions:
contents: read
issues: write

jobs:
dast:
runs-on: ubuntu-latest

steps:
- name: Checkout Repo
uses: actions/checkout@v4

      - name: Start Mutillidae Container
      - name: Start OWASP Juice Shop Container
run: |
          docker run -d -p 8080:80 --name mutillidae citizenstig/dvwa
          sleep 20
          docker run -d -p 8080:3000 --name juice-shop bkimminich/juice-shop
          sleep 30

     - name: Run ZAP Full Scan
uses: zaproxy/action-full-scan@v0.12.0
with:
target: 'http://localhost:8080'
fail_action: false


- name: Upload Reports
uses: actions/upload-artifact@v4
with:
name: dast-reports
path: |
           zap_report.html
           zap_report.json
